format = """
$kubernetes\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$buf\
$c\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$custom\
$sudo\
$line_break\
$jobs\
$status\
$shell\
$hostname\
$directory\
$character"""
right_format = """$cmd_duration"""
add_newline = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold orange)"

[username]
style_user = "green bold"
style_root = "black bold"
format = """[$user]($style) """
disabled = false
show_always = false

[time]
disabled = false
format = '[$time]($style) '
time_format = "%T"
utc_time_offset = "-5"

[cmd_duration]
min_time = 4

[directory]
home_symbol = "home"
